@startuml

[*] --> PENDING
PENDING --> PROCESSING
PROCESSING --> CANCELLED
PROCESSING --> SHIPPED
PROCESSING --> PAID

PAID --> CANCELLED
PAID --> SHIPPED
PAID --> [*]

SHIPPED --> DELIVERED
SHIPPED --> CANCELLED

DELIVERED --> [*]
DELIVERED --> CANCELLED

CANCELLED --> PENDING
CANCELLED --> [*]

@enduml