---
  title: "Общая информация"
  description: "Данный раздел описывает подход к разделению монолитного приложения на микросервисную архитектуру. Объект исследования -  компания по продаже товаров категории дом и ремонт."
  team: "Team_Analytics"
  author: "Леженкина Ольга Николаевна"
  status: "in_work"

---

== Содержание

1.  <<Цели и Задачи>>
2.  <<Выбранный Подход: "Strangler Pattern">>
3.  <<Доменные Области Бизнеса>>
4.  <<Выделение Микросервисов>>
5.  <<Технологический Стек>> - to_do
6.  <<Концепция Миграции>> - to_do

== 1. Цели и Задачи

В данном разделе описываются основные цели и конкретные задачи перехода от монолитной архитектуры к микросервисной. 
Основная цель - повышение гибкости, масштабируемости, отказоустойчивости и скорости разработки.

== 2. Выбранный Подход: "Strangler Pattern"

Здесь описывается паттерн "Strangler", который будет использоваться для постепенной миграции, с описанием принципов и преимуществ этого подхода.

== 3. Доменные Области Бизнеса

Здесь перечислены основные доменные области бизнеса, такие как каталог продукции, запасы, цены, заказы, пользователи, доставка, платежи и управление бэкофисом.

== 4. Выделение Микросервисов

В этом разделе приводятся выделенные микросервисы, соответствующие доменным областям, и описывается их взаимодействие друг с другом.

== 5. Технологический Стек

Данный раздел описывает используемый технологический стек, включая фреймворки, базы данных, инструменты контейнеризации и оркестраци.

== 6. Концепция Миграции

Данный раздел содержит план постепенной миграции, который состоит из нескольких этапов, начиная с выделения менее критичных сервисов и заканчивая выделением более сложных и нагруженных.

